stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  RUNNER_ID: ${CI_JOB_ID}
  SONAR_SERVER: 'https://sonar-cathay.akachains.io'
  CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}
  IMAGE_NAME: ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}
  GIT_SUBMODULE_STRATEGY: recursive
  REPO_MANIFEST_NAME: exchange-core
  REPO_MANIFEST_URL: git@gitlab.com:akachain/gitops/exchange-core.git
  REPO_MANIFEST_BRANCH: master
  REPO_MANIFEST_ENV_DEV: ./clusters/k8s-dev/develop
  REPO_MANIFEST_ENV_QA: ./clusters/k8s-qa/develop
  REPO_MANIFEST_ENV_UAT: ./clusters/k8s-uat/develop
  REPO_MANIFEST_ENV_TEST: ./clusters/k8s-test/develop
  REPO_MANIFEST_TAG_IMAGE: image_iao_service



build:
  tags:
    - build
    - akcCluster
  stage: build
  script:
    - chmod 777 -R ./cicd
    - ./cicd/build.sh
    - ./cicd/updateManifest.sh
  only:
    - develop
    - test
    - qa
    - uat

