---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: %NAMESPACE%
  name: %STS_NAME%
spec:
  selector:
    matchLabels:
      app: %STS_NAME%
      tier: %NAMESPACE%
  serviceName: %STS_NAME%
  replicas: 1
  template:
    metadata:
      labels:
        app: %STS_NAME%
        tier: %NAMESPACE%
        type: stateful
    spec:
      containers:
        - name: %STS_NAME%
          image: %CONTAINER_RELEASE_IMAGE%
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "600m"
          env:
          - name: NODE_ENV
            value: %NODE_ENV%
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: akc-ca-data
              mountPath: /shared
            - name: artifacts-efs
              mountPath: /data/app/artifacts/
            - name: wallet
              mountPath: /data/app/wallet/
      volumes:
      - name: akc-ca-data
        nfs:
          server: fs-d5a78b94.efs.ap-southeast-1.amazonaws.com
          path: /pvs/efs-pvc-d250e3d1-a2ae-451c-9de8-b0c755dc7dcb/akc20/akc-ca-data
      - name: artifacts-efs
        nfs:
          server: fs-d5a78b94.efs.ap-southeast-1.amazonaws.com
          path: /pvs/efs-pvc-d250e3d1-a2ae-451c-9de8-b0c755dc7dcb/akc20/admin-v2/artifacts/
      - name: wallet
        nfs:
          server: fs-d5a78b94.efs.ap-southeast-1.amazonaws.com
          path: /pvs/efs-pvc-d250e3d1-a2ae-451c-9de8-b0c755dc7dcb/akc20/admin-v2/wallet/
      imagePullSecrets:
        - name: regcred
